
server:
  port: 8080

management:
  server:
    port: 8080
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"