version: "3"

services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus-linux-arm64
    build: ./prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always

  shellymetrics:
    container_name: shellymetrics
    image: shellymetrics:1.0.0
    hostname: shellymetrics
    ports:
      - "8080:8080"

volumes:
  db-data:
  prometheus_data: { }
  grafana_data: { }
